# Chapter 7 problem set 2

In [2]:
import numpy as np
import pandas as pd
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)
from numpy import nan as NA

# Min-Yao

## 7-1

## 1. Import my RNA-Seq CPM data from 'Expression Browser_CPM_practice.xlsx' file. Please made the Itag number become the row index. How many genes in this data set? [Expression Browser_CPM_practice.xlsx](https://github.com/UCD-pbio-rclub/python-data-analysis_MinYaoJ/blob/master/Expression%20Browser_CPM_practice.xlsx)

In [17]:
xlsx = pd.ExcelFile('HW7/Expression Browser_CPM_practice.xlsx')
RNASeq = pd.read_excel(xlsx, 'Expression Browser_CPM')
RNASeq

,Name,6_c1,6_c2,6_c3,6_c4,6_c5,6_c6,6_c7,6_t1,6_t2,...,3_t5,2_c1,2_c2,2_c3,2_c4,2_c5,2_t1,2_t2,2_t3,2_t4
0,Solyc00g005000.3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,Solyc00g005005.1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,Solyc00g005040.3,0.000000,0.136237,0.000000,0.000000,0.000000,0.000000,0.000000,0.075741,0.303100,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,Solyc00g005050.3,49.947944,50.680249,42.857629,46.142383,40.925485,49.050587,49.010294,47.224546,42.282470,...,46.069768,39.626619,33.601760,38.848960,28.487619,42.516459,47.526986,47.021348,51.069134,44.480035
4,Solyc00g005055.1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,Solyc00g005060.1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,Solyc00g005080.2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.305098,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,Solyc00g005081.1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,Solyc00g005082.1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,Solyc00g005084.1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34869,Solyc12g100280.2,2.261794,1.907321,1.833481,2.454382,0.553047,3.046620,0.690286,1.969267,0.757750,...,1.220391,4.627926,3.159140,2.404936,1.340594,0.812416,0.258299,1.944492,1.480265,3.268501
34870,Solyc12g100290.2,9.612623,6.811861,5.042074,4.417888,3.318283,6.702565,6.074515,6.097155,5.607353,...,4.118820,7.375757,4.020723,3.144916,4.580362,7.853359,5.811724,5.303160,5.674348,4.263262
34871,Solyc12g100310.2,88.209955,72.069494,69.213925,87.866877,100.101524,91.703271,103.266761,91.684543,72.289383,...,67.426615,90.244562,67.634312,78.807891,72.838931,86.928556,61.475123,77.956445,84.868512,84.554698
34872,Solyc12g100300.2,0.753931,0.000000,1.145926,0.245438,0.000000,0.304662,0.276114,0.265094,0.303100,...,0.305098,0.144623,0.430792,0.369990,0.558581,0.000000,0.774897,0.000000,0.863488,0.852652
34873,Solyc12g100320.2,24.314282,25.340125,24.064444,28.225394,21.015790,26.505596,31.891206,24.653712,17.882908,...,30.662329,21.259536,17.088075,22.754391,22.678379,25.726520,28.671171,18.030742,18.626665,13.500330
34874,Solyc12g100330.2,108.943064,74.930476,70.589036,74.122338,83.510111,70.986253,83.524586,104.939227,70.773883,...,60.714463,93.860129,58.013295,72.333064,83.675397,56.327538,51.918066,58.865071,54.029663,60.964648
34875,Solyc12g100340.1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
34876,Solyc12g100350.2,10.178072,5.449489,11.230074,10.553843,6.083518,7.311889,8.145373,7.839199,9.396104,...,7.627445,6.941889,11.200587,11.839683,9.049008,11.373830,14.981332,9.899231,11.225341,10.373938
34877,Solyc12g100353.1,15.832556,14.441146,7.792296,9.326652,11.060942,5.483917,8.283430,12.459403,10.456955,...,9.152934,15.185383,12.492962,16.834550,11.841912,5.686915,2.970437,8.308283,4.070728,8.100198
34878,Solyc12g100357.1,3.581173,2.452270,0.916741,3.436135,1.106094,3.046620,1.932800,3.976405,3.485652,...,2.288234,4.049435,5.456696,6.289832,2.792904,1.083222,2.970437,4.419300,1.973686,4.121153

In [18]:
RNASeq = RNASeq.set_index('Name')
RNASeq

,6_c1,6_c2,6_c3,6_c4,6_c5,6_c6,6_c7,6_t1,6_t2,6_t3,...,3_t5,2_c1,2_c2,2_c3,2_c4,2_c5,2_t1,2_t2,2_t3,2_t4
Name,,,,,,,,,,,,,,,,,,,,,
Solyc00g005000.3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Solyc00g005005.1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Solyc00g005040.3,0.000000,0.136237,0.000000,0.000000,0.000000,0.000000,0.000000,0.075741,0.303100,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Solyc00g005050.3,49.947944,50.680249,42.857629,46.142383,40.925485,49.050587,49.010294,47.224546,42.282470,50.970454,...,46.069768,39.626619,33.601760,38.848960,28.487619,42.516459,47.526986,47.021348,51.069134,44.480035
Solyc00g005055.1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Solyc00g005060.1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Solyc00g005080.2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.305098,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Solyc00g005081.1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Solyc00g005082.1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Solyc00g005084.1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Solyc12g100280.2,2.261794,1.907321,1.833481,2.454382,0.553047,3.046620,0.690286,1.969267,0.757750,0.350312,...,1.220391,4.627926,3.159140,2.404936,1.340594,0.812416,0.258299,1.944492,1.480265,3.268501
Solyc12g100290.2,9.612623,6.811861,5.042074,4.417888,3.318283,6.702565,6.074515,6.097155,5.607353,4.729217,...,4.118820,7.375757,4.020723,3.144916,4.580362,7.853359,5.811724,5.303160,5.674348,4.263262
Solyc12g100310.2,88.209955,72.069494,69.213925,87.866877,100.101524,91.703271,103.266761,91.684543,72.289383,76.368104,...,67.426615,90.244562,67.634312,78.807891,72.838931,86.928556,61.475123,77.956445,84.868512,84.554698
Solyc12g100300.2,0.753931,0.000000,1.145926,0.245438,0.000000,0.304662,0.276114,0.265094,0.303100,0.000000,...,0.305098,0.144623,0.430792,0.369990,0.558581,0.000000,0.774897,0.000000,0.863488,0.852652
Solyc12g100320.2,24.314282,25.340125,24.064444,28.225394,21.015790,26.505596,31.891206,24.653712,17.882908,33.805147,...,30.662329,21.259536,17.088075,22.754391,22.678379,25.726520,28.671171,18.030742,18.626665,13.500330
Solyc12g100330.2,108.943064,74.930476,70.589036,74.122338,83.510111,70.986253,83.524586,104.939227,70.773883,71.288574,...,60.714463,93.860129,58.013295,72.333064,83.675397,56.327538,51.918066,58.865071,54.029663,60.964648
Solyc12g100340.1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Solyc12g100350.2,10.178072,5.449489,11.230074,10.553843,6.083518,7.311889,8.145373,7.839199,9.396104,10.334216,...,7.627445,6.941889,11.200587,11.839683,9.049008,11.373830,14.981332,9.899231,11.225341,10.373938
Solyc12g100353.1,15.832556,14.441146,7.792296,9.326652,11.060942,5.483917,8.283430,12.459403,10.456955,12.085778,...,9.152934,15.185383,12.492962,16.834550,11.841912,5.686915,2.970437,8.308283,4.070728,8.100198
Solyc12g100357.1,3.581173,2.452270,0.916741,3.436135,1.106094,3.046620,1.932800,3.976405,3.485652,1.401250,...,2.288234,4.049435,5.456696,6.289832,2.792904,1.083222,2.970437,4.419300,1.973686,4.121153

### 2. Please replace all 0 with NA.

In [20]:
replaced_RNASeq = RNASeq.replace(0, NA)
replaced_RNASeq

,6_c1,6_c2,6_c3,6_c4,6_c5,6_c6,6_c7,6_t1,6_t2,6_t3,...,3_t5,2_c1,2_c2,2_c3,2_c4,2_c5,2_t1,2_t2,2_t3,2_t4
Name,,,,,,,,,,,,,,,,,,,,,
Solyc00g005000.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Solyc00g005005.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Solyc00g005040.3,NaN,0.136237,NaN,NaN,NaN,NaN,NaN,0.075741,0.303100,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Solyc00g005050.3,49.947944,50.680249,42.857629,46.142383,40.925485,49.050587,49.010294,47.224546,42.282470,50.970454,...,46.069768,39.626619,33.601760,38.848960,28.487619,42.516459,47.526986,47.021348,51.069134,44.480035
Solyc00g005055.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Solyc00g005060.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Solyc00g005080.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.305098,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Solyc00g005081.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Solyc00g005082.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Solyc00g005084.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Solyc12g100280.2,2.261794,1.907321,1.833481,2.454382,0.553047,3.046620,0.690286,1.969267,0.757750,0.350312,...,1.220391,4.627926,3.159140,2.404936,1.340594,0.812416,0.258299,1.944492,1.480265,3.268501
Solyc12g100290.2,9.612623,6.811861,5.042074,4.417888,3.318283,6.702565,6.074515,6.097155,5.607353,4.729217,...,4.118820,7.375757,4.020723,3.144916,4.580362,7.853359,5.811724,5.303160,5.674348,4.263262
Solyc12g100310.2,88.209955,72.069494,69.213925,87.866877,100.101524,91.703271,103.266761,91.684543,72.289383,76.368104,...,67.426615,90.244562,67.634312,78.807891,72.838931,86.928556,61.475123,77.956445,84.868512,84.554698
Solyc12g100300.2,0.753931,NaN,1.145926,0.245438,NaN,0.304662,0.276114,0.265094,0.303100,NaN,...,0.305098,0.144623,0.430792,0.369990,0.558581,NaN,0.774897,NaN,0.863488,0.852652
Solyc12g100320.2,24.314282,25.340125,24.064444,28.225394,21.015790,26.505596,31.891206,24.653712,17.882908,33.805147,...,30.662329,21.259536,17.088075,22.754391,22.678379,25.726520,28.671171,18.030742,18.626665,13.500330
Solyc12g100330.2,108.943064,74.930476,70.589036,74.122338,83.510111,70.986253,83.524586,104.939227,70.773883,71.288574,...,60.714463,93.860129,58.013295,72.333064,83.675397,56.327538,51.918066,58.865071,54.029663,60.964648
Solyc12g100340.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Solyc12g100350.2,10.178072,5.449489,11.230074,10.553843,6.083518,7.311889,8.145373,7.839199,9.396104,10.334216,...,7.627445,6.941889,11.200587,11.839683,9.049008,11.373830,14.981332,9.899231,11.225341,10.373938
Solyc12g100353.1,15.832556,14.441146,7.792296,9.326652,11.060942,5.483917,8.283430,12.459403,10.456955,12.085778,...,9.152934,15.185383,12.492962,16.834550,11.841912,5.686915,2.970437,8.308283,4.070728,8.100198
Solyc12g100357.1,3.581173,2.452270,0.916741,3.436135,1.106094,3.046620,1.932800,3.976405,3.485652,1.401250,...,2.288234,4.049435,5.456696,6.289832,2.792904,1.083222,2.970437,4.419300,1.973686,4.121153

### 3. We want to remove the genes that have no expression in all samples. How many genes left after we remove these genes.

In [22]:
reduced_RNASeq = replaced_RNASeq.dropna(how='all')
reduced_RNASeq

,6_c1,6_c2,6_c3,6_c4,6_c5,6_c6,6_c7,6_t1,6_t2,6_t3,...,3_t5,2_c1,2_c2,2_c3,2_c4,2_c5,2_t1,2_t2,2_t3,2_t4
Name,,,,,,,,,,,,,,,,,,,,,
Solyc00g005040.3,NaN,0.136237,NaN,NaN,NaN,NaN,NaN,0.075741,0.303100,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Solyc00g005050.3,49.947944,50.680249,42.857629,46.142383,40.925485,49.050587,49.010294,47.224546,42.282470,50.970454,...,46.069768,39.626619,33.601760,38.848960,28.487619,42.516459,47.526986,47.021348,51.069134,44.480035
Solyc00g005080.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.305098,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Solyc00g005092.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.426326
Solyc00g005094.1,0.376966,0.408712,NaN,0.245438,NaN,NaN,0.414172,NaN,0.151550,0.175156,...,0.152549,NaN,0.143597,NaN,NaN,NaN,NaN,NaN,NaN,0.142109
Solyc00g005096.1,NaN,0.681186,0.916741,0.736315,0.553047,0.913986,0.414172,0.643799,0.151550,0.175156,...,0.610196,1.012359,1.005181,0.739980,3.239768,1.354027,1.678942,0.176772,0.370066,2.557957
Solyc00g005283.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Solyc00g005287.1,NaN,0.136237,NaN,NaN,0.553047,NaN,NaN,NaN,0.151550,NaN,...,NaN,0.289245,NaN,0.184995,0.111716,0.270805,NaN,NaN,NaN,NaN
Solyc00g005840.3,13.759245,9.264132,8.250667,12.026472,11.613989,14.319115,9.664002,9.240408,9.699204,7.006248,...,5.034114,10.123589,8.615836,11.469693,9.495873,10.019802,9.427907,5.833476,5.550993,7.531763
Solyc00g005850.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Solyc12g100270.2,NaN,NaN,0.229185,0.245438,NaN,NaN,NaN,1.401209,NaN,29.951710,...,9.763130,NaN,0.143597,NaN,NaN,2.437249,3.616184,1.944492,1.850331,0.426326
Solyc12g100280.2,2.261794,1.907321,1.833481,2.454382,0.553047,3.046620,0.690286,1.969267,0.757750,0.350312,...,1.220391,4.627926,3.159140,2.404936,1.340594,0.812416,0.258299,1.944492,1.480265,3.268501
Solyc12g100290.2,9.612623,6.811861,5.042074,4.417888,3.318283,6.702565,6.074515,6.097155,5.607353,4.729217,...,4.118820,7.375757,4.020723,3.144916,4.580362,7.853359,5.811724,5.303160,5.674348,4.263262
Solyc12g100310.2,88.209955,72.069494,69.213925,87.866877,100.101524,91.703271,103.266761,91.684543,72.289383,76.368104,...,67.426615,90.244562,67.634312,78.807891,72.838931,86.928556,61.475123,77.956445,84.868512,84.554698
Solyc12g100300.2,0.753931,NaN,1.145926,0.245438,NaN,0.304662,0.276114,0.265094,0.303100,NaN,...,0.305098,0.144623,0.430792,0.369990,0.558581,NaN,0.774897,NaN,0.863488,0.852652
Solyc12g100320.2,24.314282,25.340125,24.064444,28.225394,21.015790,26.505596,31.891206,24.653712,17.882908,33.805147,...,30.662329,21.259536,17.088075,22.754391,22.678379,25.726520,28.671171,18.030742,18.626665,13.500330
Solyc12g100330.2,108.943064,74.930476,70.589036,74.122338,83.510111,70.986253,83.524586,104.939227,70.773883,71.288574,...,60.714463,93.860129,58.013295,72.333064,83.675397,56.327538,51.918066,58.865071,54.029663,60.964648
Solyc12g100350.2,10.178072,5.449489,11.230074,10.553843,6.083518,7.311889,8.145373,7.839199,9.396104,10.334216,...,7.627445,6.941889,11.200587,11.839683,9.049008,11.373830,14.981332,9.899231,11.225341,10.373938
Solyc12g100353.1,15.832556,14.441146,7.792296,9.326652,11.060942,5.483917,8.283430,12.459403,10.456955,12.085778,...,9.152934,15.185383,12.492962,16.834550,11.841912,5.686915,2.970437,8.308283,4.070728,8.100198
Solyc12g100357.1,3.581173,2.452270,0.916741,3.436135,1.106094,3.046620,1.932800,3.976405,3.485652,1.401250,...,2.288234,4.049435,5.456696,6.289832,2.792904,1.083222,2.970437,4.419300,1.973686,4.121153

# 7-2 prectice question

#### 1. Using the same data from last week. (Import my RNA-Seq CPM data from 'Expression Browser_CPM_practice.xlsx' file.) Remove the genes that have no expression in all samples and keep other no expression as "0". Check the data distribution in each sample.

In [24]:
reduced_RNASeq = RNASeq.replace(NA, 0)
reduced_RNASeq.describe()

,6_c1,6_c2,6_c3,6_c4,6_c5,6_c6,6_c7,6_t1,6_t2,6_t3,...,3_t5,2_c1,2_c2,2_c3,2_c4,2_c5,2_t1,2_t2,2_t3,2_t4
count,34879.000000,34879.000000,34879.000000,34879.000000,34879.000000,34879.000000,34879.000000,34879.000000,34879.000000,34879.000000,...,34879.000000,34879.000000,34879.000000,34879.000000,34879.000000,34879.000000,34879.000000,34879.000000,34879.000000,34879.000000
mean,27.837634,28.223531,28.609524,26.572741,26.797089,27.681007,29.305176,28.907041,27.061318,29.445887,...,32.370165,27.423190,25.792731,26.681172,28.160192,27.648370,30.419700,28.697195,28.351448,25.866459
std,154.167127,159.997758,173.741211,158.447795,164.241803,162.223576,175.627182,151.504046,149.010841,144.346305,...,179.905338,159.651562,155.280293,161.608785,162.340070,140.676000,157.379487,147.101847,151.259068,156.647928
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.565448,0.681186,0.458370,0.490876,0.553047,0.609324,0.552229,0.757411,0.757750,0.700625,...,0.762745,0.723113,0.861584,0.739980,0.782013,0.812416,0.774897,0.707088,0.740132,0.710544
75%,14.513176,15.122332,14.667852,14.971731,14.379224,14.623777,14.634060,15.413304,15.306557,15.063433,...,14.492146,15.040760,15.077713,15.169594,15.081680,14.623495,15.239631,15.025619,15.172714,15.347744
max,12737.668250,13164.330920,14629.577790,14130.122910,15457.666270,13963.879410,16121.073410,12598.993730,12763.243800,10792.599630,...,12504.433520,13895.203970,13132.975150,13235.285820,11974.183940,11524.939240,11238.194880,10325.781960,15249.070610,14770.497900

#### 2. we want to filtering outliers. Please find the genes that have any expression is higher than 15000 in any sample.

In [25]:
reduced_RNASeq[(np.abs(reduced_RNASeq) > 15000).any(1)]

,6_c1,6_c2,6_c3,6_c4,6_c5,6_c6,6_c7,6_t1,6_t2,6_t3,...,3_t5,2_c1,2_c2,2_c3,2_c4,2_c5,2_t1,2_t2,2_t3,2_t4
Name,,,,,,,,,,,,,,,,,,,,,
Solyc04g071070.2,101.026786,152.721933,129.489629,78.785664,111.162466,122.778797,164.011914,769.566954,196.105791,4508.870924,...,5902.574676,416.947231,391.876939,163.350629,550.425476,855.745289,7660.239411,1124.976912,2474.755940,173.372659
Solyc07g064160.3,7335.373974,9455.136137,11287.370270,10797.562960,10431.021240,9576.136875,9831.188897,5971.500240,7993.205342,2997.448067,...,3733.939481,11076.218390,11513.197990,11466.178160,8909.474766,5437.232249,3896.437931,8015.902431,5273.196437,12671.836070
Solyc09g010800.4,12737.668250,13164.330920,14629.577790,14130.122910,15457.666270,13963.879410,16121.073410,12598.993730,12763.243800,10792.599630,...,12504.433520,13895.203970,13132.975150,13235.285820,9783.430216,11524.939240,11238.194880,10325.781960,15249.070610,14770.497900

#### 3. we would like to transform outliers. Please change the expression level exceeding 15000 in absolute value to 15000. Please check the new data distribution in each sample.

In [26]:
reduced_RNASeq[np.abs(reduced_RNASeq) > 15000] = np.sign(reduced_RNASeq) * 15000

In [27]:
reduced_RNASeq.describe()

,6_c1,6_c2,6_c3,6_c4,6_c5,6_c6,6_c7,6_t1,6_t2,6_t3,...,3_t5,2_c1,2_c2,2_c3,2_c4,2_c5,2_t1,2_t2,2_t3,2_t4
count,34879.000000,34879.000000,34879.000000,34879.000000,34879.000000,34879.000000,34879.000000,34879.000000,34879.000000,34879.000000,...,34879.000000,34879.000000,34879.000000,34879.000000,34879.000000,34879.000000,34879.000000,34879.000000,34879.000000,34879.000000
mean,27.837634,28.223531,28.609524,26.572741,26.783968,27.681007,29.273034,28.907041,27.061318,29.445887,...,32.370165,27.423190,25.792731,26.681172,28.160192,27.648370,30.419700,28.697195,28.344307,25.866459
std,154.167127,159.997758,173.741211,158.447795,163.022728,162.223576,172.761322,151.504046,149.010841,144.346305,...,179.905338,159.651562,155.280293,161.608785,162.340070,140.676000,157.379487,147.101847,150.544664,156.647928
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.565448,0.681186,0.458370,0.490876,0.553047,0.609324,0.552229,0.757411,0.757750,0.700625,...,0.762745,0.723113,0.861584,0.739980,0.782013,0.812416,0.774897,0.707088,0.740132,0.710544
75%,14.513176,15.122332,14.667852,14.971731,14.379224,14.623777,14.634060,15.413304,15.306557,15.063433,...,14.492146,15.040760,15.077713,15.169594,15.081680,14.623495,15.239631,15.025619,15.172714,15.347744
max,12737.668250,13164.330920,14629.577790,14130.122910,15000.000000,13963.879410,15000.000000,12598.993730,12763.243800,10792.599630,...,12504.433520,13895.203970,13132.975150,13235.285820,11974.183940,11524.939240,11238.194880,10325.781960,15000.000000,14770.497900

In [28]:
np.sign(reduced_RNASeq)

,6_c1,6_c2,6_c3,6_c4,6_c5,6_c6,6_c7,6_t1,6_t2,6_t3,...,3_t5,2_c1,2_c2,2_c3,2_c4,2_c5,2_t1,2_t2,2_t3,2_t4
Name,,,,,,,,,,,,,,,,,,,,,
Solyc00g005000.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Solyc00g005005.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Solyc00g005040.3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Solyc00g005050.3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Solyc00g005055.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Solyc00g005060.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Solyc00g005080.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Solyc00g005081.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Solyc00g005082.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Solyc00g005084.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Solyc12g100280.2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Solyc12g100290.2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Solyc12g100310.2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Solyc12g100300.2,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,...,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0
Solyc12g100320.2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Solyc12g100330.2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Solyc12g100340.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Solyc12g100350.2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Solyc12g100353.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Solyc12g100357.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

## Kae

### 1. Create a random DNA sequence of length 30. Using regex, please convert the DNA sequence to RNA.

In [22]:
import re
import random

In [10]:
DNA = ''.join([random.choice('AGTC') for x in range(30)])
DNA

'GCACGTGCCCTACTATGTTTGCTCAGATAC'

In [14]:
RNA = DNA.replace('T','U')
RNA

'GCACGUGCCCUACUAUGUUUGCUCAGAUAC'

### 2. I work for telemarketing company and I've been given a list of phone numbers the branch needs to call today. Luckily for me, I'm only responsible for calling properly formatted (XXX)XXX-XXXX numbers with area codes of either 603 or 503. What regular expression can I use to pull these numbers from my list? Try this if you're having trouble.

In [9]:
# ^\((?:603|503)\)\d{3}-\d{4}$

## Joel

### 1.Create a function to define if a string is a palindrome or not. (A palindrome is a word or sentence that has the same letters backwards and forwards)

### a) Replacing whitespaces is a good way to start b) Watch out for upper/lower case differences

In [41]:
def palindrome(string):
    
    if(string.replace(" ","").lower()==string[::-1].replace(" ","").lower()):
        print("The string is a palindrome")
    else:
        print("The string isn't a palindrome")

In [42]:
palindrome('palindrome')

The string isn't a palindrome

In [37]:
### Try with words/sentences like:

###"Was it a car or a cat I saw"
###"Ceci n'est pas un palindrome"
###GCCTTCCG
###CGTAATGC
###Anita lava la tina
###kayak

In [43]:
palindrome("Was it a car or a cat I saw")

The string is a palindrome

In [44]:
palindrome("Ceci n'est pas un palindrome")

The string isn't a palindrome

In [45]:
palindrome("GCCTTCCG")

The string is a palindrome

In [46]:
palindrome("Anita lava la tina")

The string is a palindrome

# John

## Find me Beer using this https://api.openbrewerydb.org/breweries?

### 1. Create a dataframe using the api address above with every brewery in the database. Will need to use page and per_page as parameters. per_page max is 50

In [19]:
import requests
import re

In [9]:
url = 'https://api.openbrewerydb.org/breweries?page=0&per_page=50'

In [10]:
resp = requests.get(url)
resp

In [11]:
data = resp.json()

In [12]:
data[0]

{'id': 2,
 'name': 'Avondale Brewing Co',
 'brewery_type': 'micro',
 'street': '201 41st St S',
 'city': 'Birmingham',
 'state': 'Alabama',
 'postal_code': '35222-1932',
 'country': 'United States',
 'longitude': '-86.774322',
 'latitude': '33.524521',
 'phone': '2057775456',
 'website_url': 'http://www.avondalebrewing.com',
 'updated_at': '2018-08-23T23:19:57.825Z',
 'tag_list': []}

## 2. Filter this data set down to only micro breweries in states that with begin and end with the same letter

In [13]:
Beer = pd.DataFrame(data, columns=['id','name','brewery_type','street','city','state','postal_code','country','longitude','latitude','phone','website_url','updated_at','tag_list'])

In [14]:
Beer

,id,name,brewery_type,street,city,state,postal_code,country,longitude,latitude,phone,website_url,updated_at,tag_list
0,2,Avondale Brewing Co,micro,201 41st St S,Birmingham,Alabama,35222-1932,United States,-86.774322,33.524521,2057775456,http://www.avondalebrewing.com,2018-08-23T23:19:57.825Z,[]
1,4,Band of Brothers Brewing Company,micro,1605 23rd Ave,Tuscaloosa,Alabama,35401-4653,United States,-87.5621551272424,33.1984907123707,2052665137,http://www.bandofbrosbrewing.com,2018-08-23T23:19:59.462Z,[]
2,44,Trim Tab Brewing,micro,2721 5th Ave S,Birmingham,Alabama,35233-3401,United States,-86.7914000624146,33.5128492349817,2057030536,http://www.trimtabbrewing.com,2018-08-23T23:20:31.423Z,[]
3,46,Yellowhammer Brewery,micro,2600 Clinton Ave W,Huntsville,Alabama,35805-3046,United States,-86.5932014,34.7277523,2569755950,http://www.yellowhammerbrewery.com,2018-08-23T23:20:33.102Z,[]
4,55,Bearpaw River Brewing Co,micro,4605 E Palmer Wasilla Hwy,Wasilla,Alaska,99654-7679,United States,-149.4127103,61.5752695,,http://bearpawriverbrewing.com,2018-08-23T23:20:40.743Z,[]
5,76,King Street Brewing Co,micro,9050 King Street,Anchorage,Alaska,99515,United States,-149.879076042937,61.1384893547315,9073365464,http://www.kingstreetbrewing.com,2018-08-23T23:20:57.179Z,[]
6,94,1912 Brewing,micro,2045 N Forbes Blvd Ste 105,Tucson,Arizona,85745-1444,United States,-110.992750525872,32.2467372722906,5202564851,http://www.1912brewing.com,2018-08-23T23:21:11.302Z,[]
7,98,Bad Water Brewing,contract,4216 N Brown Ave,Scottsdale,Arizona,85251-3914,United States,-111.924474347826,33.4972615652174,5207459175,http://www.badwaterbrewing.com,2018-08-23T23:21:15.169Z,[]
8,104,BJs Restaurant & Brewery - Chandler,brewpub,3155 W Chandler Blvd,Chandler,Arizona,85226-5175,United States,-111.911126,33.3053455,4809170631,http://www.bjsrestaurants.com,2018-08-23T23:21:21.165Z,[]
9,107,BlackRock Brewers,micro,1664 S Research Loop Ste 200,Tucson,Arizona,85710-6767,United States,-110.821778571134,32.201608314954,5202073203,http://www.brb.beer,2018-08-23T23:21:23.794Z,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40,543,Dry River Brewing,micro,671 S Anderson St,Los Angeles,California,90023-1110,United States,-118.223301521739,34.0363873913043,2133755235,http://www.dryriverbrewing.com,2018-08-23T23:27:38.017Z,[]
41,562,Eight Bridges Brewing,micro,332 Earhart Way,Livermore,California,94551-9309,United States,-121.814589292069,37.6989500360251,9259619160,http://www.eightbridgesbrewing.com,2018-08-23T23:27:54.121Z,[]
42,573,Eppig Brewing,micro,3052 El Cajon Blvd Ste 103,San Diego,California,92104-1399,United States,-117.128732,32.755723,6195011840,http://www.eppigbrewing.com,2018-08-23T23:28:03.844Z,[]
43,574,Escape Craft Brewery,micro,721 Nevada St Ste 401,Redlands,California,92373-8053,United States,-117.217577166632,34.0603401026307,9097133727,http://www.escapecraftbrewery.com,2018-08-23T23:28:04.869Z,[]
44,592,Fieldwork Brewing Co,regional,1160 6th St,Berkeley,California,94710-1247,United States,-122.302214696327,37.88157297059,5108981203,http://www.fieldworkbrewing.com,2018-08-23T23:28:19.100Z,[]
45,612,Fort Point Beer Company,regional,644 Mason St,San Francisco,California,94129-1600,United States,-122.410227755102,37.789461244898,4159064021,http://www.fortpointbeer.com,2018-08-23T23:28:36.026Z,[]
46,615,Fountainhead Brewing Co,micro,4621 24th St,Sacramento,California,95822-1412,United States,-121.483117319123,38.5332279038371,9162284610,http://www.fountainheadbrewingco.com,2018-08-23T23:28:38.770Z,[]
47,623,Geartooth AleWerks,micro,1635 S 7th St,San Jose,California,95112-5932,United States,-121.866477333785,37.315251291037,4084832679,http://www.geartoothalewerks.com,2018-08-23T23:28:45.233Z,[]
48,633,Golden State Brewery,micro,1252 Memorex Dr,Santa Clara,California,95050-2812,United States,-121.950316757586,37.3625383916082,4087272337,http://www.goldenstate.beer,2018-08-23T23:28:53.181Z,[]
49,654,Hangar 24 Craft Brewery,regional,1710 Sessums Dr,Redlands,California,92374-1909,United States,-117.1419134,34.0831712,9093891400,http://www.hangar24brewery.com,2018-08-23T23:29:10.400Z,[]

In [31]:
microbeer=Beer[Beer['brewery_type'].str.match('micro')]
microbeer

,id,name,brewery_type,street,city,state,postal_code,country,longitude,latitude,phone,website_url,updated_at,tag_list
0,2,Avondale Brewing Co,micro,201 41st St S,Birmingham,Alabama,35222-1932,United States,-86.774322,33.524521,2057775456,http://www.avondalebrewing.com,2018-08-23T23:19:57.825Z,[]
1,4,Band of Brothers Brewing Company,micro,1605 23rd Ave,Tuscaloosa,Alabama,35401-4653,United States,-87.5621551272424,33.1984907123707,2052665137,http://www.bandofbrosbrewing.com,2018-08-23T23:19:59.462Z,[]
2,44,Trim Tab Brewing,micro,2721 5th Ave S,Birmingham,Alabama,35233-3401,United States,-86.7914000624146,33.5128492349817,2057030536,http://www.trimtabbrewing.com,2018-08-23T23:20:31.423Z,[]
3,46,Yellowhammer Brewery,micro,2600 Clinton Ave W,Huntsville,Alabama,35805-3046,United States,-86.5932014,34.7277523,2569755950,http://www.yellowhammerbrewery.com,2018-08-23T23:20:33.102Z,[]
4,55,Bearpaw River Brewing Co,micro,4605 E Palmer Wasilla Hwy,Wasilla,Alaska,99654-7679,United States,-149.4127103,61.5752695,,http://bearpawriverbrewing.com,2018-08-23T23:20:40.743Z,[]
5,76,King Street Brewing Co,micro,9050 King Street,Anchorage,Alaska,99515,United States,-149.879076042937,61.1384893547315,9073365464,http://www.kingstreetbrewing.com,2018-08-23T23:20:57.179Z,[]
6,94,1912 Brewing,micro,2045 N Forbes Blvd Ste 105,Tucson,Arizona,85745-1444,United States,-110.992750525872,32.2467372722906,5202564851,http://www.1912brewing.com,2018-08-23T23:21:11.302Z,[]
9,107,BlackRock Brewers,micro,1664 S Research Loop Ste 200,Tucson,Arizona,85710-6767,United States,-110.821778571134,32.201608314954,5202073203,http://www.brb.beer,2018-08-23T23:21:23.794Z,[]
10,127,Dragoon Brewing Co,micro,1859 W Grant Rd Ste 111,Tucson,Arizona,85745-1214,United States,-111.005452051979,32.2504946147872,5203293606,http://www.dragoonbrewing.com,2018-08-23T23:21:40.563Z,[]
11,141,Grand Canyon Brewing Company,micro,233 W Route 66,Williams,Arizona,86046-2530,United States,-112.1892168,35.2500282,8005132072,http://www.grandcanyonbrewingco.com,2018-08-23T23:21:53.397Z,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35,479,Chula Vista Brewery,micro,294 Third Ave,Chula Vista,California,91910-2701,United States,-117.080369,32.641495,6196168806,http://www.chulavistabrewery.com,2018-08-23T23:26:42.768Z,[]
36,54,Barnaby Brewing Company,micro,206 N Franklin St,Juneau,Alaska,99801-1225,United States,-134.407726539973,58.3017758843016,9074190916,http://www.barnabybrew.com,2018-08-23T23:20:39.859Z,[]
38,508,Craftsman Brewing Co,micro,1260 Lincoln Ave Ste 100,Pasadena,California,91103-2465,United States,-118.1595567,34.1674435,6262962537,http://www.craftsmanbrewing.com,2018-08-23T23:27:07.240Z,[]
40,543,Dry River Brewing,micro,671 S Anderson St,Los Angeles,California,90023-1110,United States,-118.223301521739,34.0363873913043,2133755235,http://www.dryriverbrewing.com,2018-08-23T23:27:38.017Z,[]
41,562,Eight Bridges Brewing,micro,332 Earhart Way,Livermore,California,94551-9309,United States,-121.814589292069,37.6989500360251,9259619160,http://www.eightbridgesbrewing.com,2018-08-23T23:27:54.121Z,[]
42,573,Eppig Brewing,micro,3052 El Cajon Blvd Ste 103,San Diego,California,92104-1399,United States,-117.128732,32.755723,6195011840,http://www.eppigbrewing.com,2018-08-23T23:28:03.844Z,[]
43,574,Escape Craft Brewery,micro,721 Nevada St Ste 401,Redlands,California,92373-8053,United States,-117.217577166632,34.0603401026307,9097133727,http://www.escapecraftbrewery.com,2018-08-23T23:28:04.869Z,[]
46,615,Fountainhead Brewing Co,micro,4621 24th St,Sacramento,California,95822-1412,United States,-121.483117319123,38.5332279038371,9162284610,http://www.fountainheadbrewingco.com,2018-08-23T23:28:38.770Z,[]
47,623,Geartooth AleWerks,micro,1635 S 7th St,San Jose,California,95112-5932,United States,-121.866477333785,37.315251291037,4084832679,http://www.geartoothalewerks.com,2018-08-23T23:28:45.233Z,[]
48,633,Golden State Brewery,micro,1252 Memorex Dr,Santa Clara,California,95050-2812,United States,-121.950316757586,37.3625383916082,4087272337,http://www.goldenstate.beer,2018-08-23T23:28:53.181Z,[]

In [20]:
pattern1 = r'^([A-Z]).*\1$'

In [21]:
pattern2 = r'\b(\w)\w*1\b'

In [23]:
regex = re.compile(pattern1, flags=re.IGNORECASE)

In [24]:
regex.match(microbeer['state'])

TypeError: expected string or bytes-like object

In [25]:
microbeer[regex.match(microbeer['state'])]

TypeError: expected string or bytes-like object

In [39]:
microbeer_Arizona=microbeer[microbeer['state'].str.match('Arizona')]
microbeer_Arizona

,id,name,brewery_type,street,city,state,postal_code,country,longitude,latitude,phone,website_url,updated_at,tag_list
6,94,1912 Brewing,micro,2045 N Forbes Blvd Ste 105,Tucson,Arizona,85745-1444,United States,-110.992750525872,32.2467372722906,5202564851,http://www.1912brewing.com,2018-08-23T23:21:11.302Z,[]
9,107,BlackRock Brewers,micro,1664 S Research Loop Ste 200,Tucson,Arizona,85710-6767,United States,-110.821778571134,32.201608314954,5202073203,http://www.brb.beer,2018-08-23T23:21:23.794Z,[]
10,127,Dragoon Brewing Co,micro,1859 W Grant Rd Ste 111,Tucson,Arizona,85745-1214,United States,-111.005452051979,32.2504946147872,5203293606,http://www.dragoonbrewing.com,2018-08-23T23:21:40.563Z,[]
11,141,Grand Canyon Brewing Company,micro,233 W Route 66,Williams,Arizona,86046-2530,United States,-112.1892168,35.2500282,8005132072,http://www.grandcanyonbrewingco.com,2018-08-23T23:21:53.397Z,[]
12,163,Mudshark Brewing Co,micro,210 Swanson Ave,Lake Havasu City,Arizona,86403-0966,United States,-114.342433477881,34.4689736300844,9284532981,http://www.mudsharkbrewingco.com,2018-08-23T23:22:12.542Z,[]
13,182,Richter Aleworks,micro,8279 W Lake Pleasant Pkwy Ste 110,Peoria,Arizona,85382-7434,United States,-112.238054093359,33.6687744976834,6029086553,http://www.richteraleworks.com,2018-08-23T23:22:29.385Z,[]
16,219,Wren House Brewing Company,micro,2125 N 24th St,Phoenix,Arizona,85008-2713,United States,-112.0301125,33.516633,6022449184,http://www.wrenhousebrewing.com,2018-08-23T23:22:59.255Z,[]

In [36]:
microbeer_Alabama=microbeer[microbeer['state'].str.match('Alabama')]
microbeer_Alabama

,id,name,brewery_type,street,city,state,postal_code,country,longitude,latitude,phone,website_url,updated_at,tag_list
0,2,Avondale Brewing Co,micro,201 41st St S,Birmingham,Alabama,35222-1932,United States,-86.774322,33.524521,2057775456,http://www.avondalebrewing.com,2018-08-23T23:19:57.825Z,[]
1,4,Band of Brothers Brewing Company,micro,1605 23rd Ave,Tuscaloosa,Alabama,35401-4653,United States,-87.5621551272424,33.1984907123707,2052665137,http://www.bandofbrosbrewing.com,2018-08-23T23:19:59.462Z,[]
2,44,Trim Tab Brewing,micro,2721 5th Ave S,Birmingham,Alabama,35233-3401,United States,-86.7914000624146,33.5128492349817,2057030536,http://www.trimtabbrewing.com,2018-08-23T23:20:31.423Z,[]
3,46,Yellowhammer Brewery,micro,2600 Clinton Ave W,Huntsville,Alabama,35805-3046,United States,-86.5932014,34.7277523,2569755950,http://www.yellowhammerbrewery.com,2018-08-23T23:20:33.102Z,[]

In [34]:
microbeer_Alaska=microbeer[microbeer['state'].str.match('Alaska')]
microbeer_Alaska

,id,name,brewery_type,street,city,state,postal_code,country,longitude,latitude,phone,website_url,updated_at,tag_list
4,55,Bearpaw River Brewing Co,micro,4605 E Palmer Wasilla Hwy,Wasilla,Alaska,99654-7679,United States,-149.4127103,61.5752695,,http://bearpawriverbrewing.com,2018-08-23T23:20:40.743Z,[]
5,76,King Street Brewing Co,micro,9050 King Street,Anchorage,Alaska,99515,United States,-149.879076042937,61.1384893547315,9073365464,http://www.kingstreetbrewing.com,2018-08-23T23:20:57.179Z,[]
36,54,Barnaby Brewing Company,micro,206 N Franklin St,Juneau,Alaska,99801-1225,United States,-134.407726539973,58.3017758843016,9074190916,http://www.barnabybrew.com,2018-08-23T23:20:39.859Z,[]

#### 3. From the breweries found in part 2, find the farthest north, south, east, and west breweries. You may need to change the dtype of the columns

# Rie

### 1. Read csv data named "sRNAalignmentToTE.ForChap7Assignment.013119.csv" in my depository.Inspect the data. (https://github.com/UCD-pbio-rclub/python-data-analysis_RieU/blob/master/sRNAalignmentToTE.ForChap7Assignment.013119.csv)

In [52]:
sRNA = pd.read_csv('HW7/sRNAalignmentToTE.ForChap7Assignment.013119.csv')

In [53]:
sRNA.head()

,totalReads,Aligned,notAligned,libName
0,1530841,37407 (2.44%),1493434 (97.56%),cot-EP-EP-1.qual.clipped.noRDNAorTDNA.Gmax_189...
1,526938,125711 (23.86%),401227 (76.14%),cot-EP-EP-1.qual.clipped.noRDNAorTDNA.Gmax_189...
2,2889626,816373 (28.25%),2073253 (71.75%),cot-EP-EP-1.qual.clipped.noRDNAorTDNA.Gmax_189...
3,1541795,40918 (2.65%),1500877 (97.35%),cot-EP-EP-2.qual.clipped.noRDNAorTDNA.Gmax_189...
4,629472,140798 (22.37%),488674 (77.63%),cot-EP-EP-2.qual.clipped.noRDNAorTDNA.Gmax_189...

### 2. Some columns have number in percentage inside of the parentheses. Remove those parentheses, then place the values inside of parentheses to the separate columns.

In [54]:
sRNA[['Aligned','Aligned%']] = sRNA.Aligned.str.split('\(|\)', expand=True).iloc[:,[0,1]]
sRNA

,totalReads,Aligned,notAligned,libName,Aligned%
0,1530841,37407,1493434 (97.56%),cot-EP-EP-1.qual.clipped.noRDNAorTDNA.Gmax_189...,2.44%
1,526938,125711,401227 (76.14%),cot-EP-EP-1.qual.clipped.noRDNAorTDNA.Gmax_189...,23.86%
2,2889626,816373,2073253 (71.75%),cot-EP-EP-1.qual.clipped.noRDNAorTDNA.Gmax_189...,28.25%
3,1541795,40918,1500877 (97.35%),cot-EP-EP-2.qual.clipped.noRDNAorTDNA.Gmax_189...,2.65%
4,629472,140798,488674 (77.63%),cot-EP-EP-2.qual.clipped.noRDNAorTDNA.Gmax_189...,22.37%
5,3283766,921828,2361938 (71.93%),cot-EP-EP-2.qual.clipped.noRDNAorTDNA.Gmax_189...,28.07%
6,503602,44673,458929 (91.13%),cot-ES-ES-1.qual.clipped.noRDNAorTDNA.Gmax_189...,8.87%
7,446023,88989,357034 (80.05%),cot-ES-ES-1.qual.clipped.noRDNAorTDNA.Gmax_189...,19.95%
8,1021143,198057,823086 (80.60%),cot-ES-ES-1.qual.clipped.noRDNAorTDNA.Gmax_189...,19.40%
9,497334,45898,451436 (90.77%),cot-ES-ES-2.qual.clipped.noRDNAorTDNA.Gmax_189...,9.23%
...,...,...,...,...,...
62,1171645,243406,928239 (79.23%),hrt-ES-ES-1.qual.clipped.noRDNAorTDNA.Gmax_189...,20.77%
63,540918,49511,491407 (90.85%),hrt-ES-ES-2.qual.clipped.noRDNAorTDNA.Gmax_189...,9.15%
64,585242,98203,487039 (83.22%),hrt-ES-ES-2.qual.clipped.noRDNAorTDNA.Gmax_189...,16.78%
65,1190588,244216,946372 (79.49%),hrt-ES-ES-2.qual.clipped.noRDNAorTDNA.Gmax_189...,20.51%
66,603379,29159,574220 (95.17%),hrt-SC-OI-1.qual.clipped.noRDNAorTDNA.Gmax_189...,4.83%
67,445210,93418,351792 (79.02%),hrt-SC-OI-1.qual.clipped.noRDNAorTDNA.Gmax_189...,20.98%
68,1854508,450682,1403826 (75.70%),hrt-SC-OI-1.qual.clipped.noRDNAorTDNA.Gmax_189...,24.30%
69,762876,31311,731565 (95.90%),hrt-SC-OI-2.qual.clipped.noRDNAorTDNA.Gmax_189...,4.10%
70,789247,111421,677826 (85.88%),hrt-SC-OI-2.qual.clipped.noRDNAorTDNA.Gmax_189...,14.12%
71,2275678,559337,1716341 (75.42%),hrt-SC-OI-2.qual.clipped.noRDNAorTDNA.Gmax_189...,24.58%

In [55]:
sRNA[['notAligned','notAligned%']] = sRNA.notAligned.str.split('\(|\)', expand=True).iloc[:,[0,1]]
sRNA

,totalReads,Aligned,notAligned,libName,Aligned%,notAligned%
0,1530841,37407,1493434,cot-EP-EP-1.qual.clipped.noRDNAorTDNA.Gmax_189...,2.44%,97.56%
1,526938,125711,401227,cot-EP-EP-1.qual.clipped.noRDNAorTDNA.Gmax_189...,23.86%,76.14%
2,2889626,816373,2073253,cot-EP-EP-1.qual.clipped.noRDNAorTDNA.Gmax_189...,28.25%,71.75%
3,1541795,40918,1500877,cot-EP-EP-2.qual.clipped.noRDNAorTDNA.Gmax_189...,2.65%,97.35%
4,629472,140798,488674,cot-EP-EP-2.qual.clipped.noRDNAorTDNA.Gmax_189...,22.37%,77.63%
5,3283766,921828,2361938,cot-EP-EP-2.qual.clipped.noRDNAorTDNA.Gmax_189...,28.07%,71.93%
6,503602,44673,458929,cot-ES-ES-1.qual.clipped.noRDNAorTDNA.Gmax_189...,8.87%,91.13%
7,446023,88989,357034,cot-ES-ES-1.qual.clipped.noRDNAorTDNA.Gmax_189...,19.95%,80.05%
8,1021143,198057,823086,cot-ES-ES-1.qual.clipped.noRDNAorTDNA.Gmax_189...,19.40%,80.60%
9,497334,45898,451436,cot-ES-ES-2.qual.clipped.noRDNAorTDNA.Gmax_189...,9.23%,90.77%
...,...,...,...,...,...,...
62,1171645,243406,928239,hrt-ES-ES-1.qual.clipped.noRDNAorTDNA.Gmax_189...,20.77%,79.23%
63,540918,49511,491407,hrt-ES-ES-2.qual.clipped.noRDNAorTDNA.Gmax_189...,9.15%,90.85%
64,585242,98203,487039,hrt-ES-ES-2.qual.clipped.noRDNAorTDNA.Gmax_189...,16.78%,83.22%
65,1190588,244216,946372,hrt-ES-ES-2.qual.clipped.noRDNAorTDNA.Gmax_189...,20.51%,79.49%
66,603379,29159,574220,hrt-SC-OI-1.qual.clipped.noRDNAorTDNA.Gmax_189...,4.83%,95.17%
67,445210,93418,351792,hrt-SC-OI-1.qual.clipped.noRDNAorTDNA.Gmax_189...,20.98%,79.02%
68,1854508,450682,1403826,hrt-SC-OI-1.qual.clipped.noRDNAorTDNA.Gmax_189...,24.30%,75.70%
69,762876,31311,731565,hrt-SC-OI-2.qual.clipped.noRDNAorTDNA.Gmax_189...,4.10%,95.90%
70,789247,111421,677826,hrt-SC-OI-2.qual.clipped.noRDNAorTDNA.Gmax_189...,14.12%,85.88%
71,2275678,559337,1716341,hrt-SC-OI-2.qual.clipped.noRDNAorTDNA.Gmax_189...,24.58%,75.42%